server:
  port: 8585
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: Mysql#803454
    url: jdbc:mysql://localhost:3306/newdb
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
